### ISSUE TITLE
Unable to Build

### ISSUE THREAD

**Issue by SteveFeldman** [JH3P/Smoker-Data-WebApp#1]
Looks like there is a compilation issue...See ISmokerTrendDao

[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/stevefeldman/Projects/candidates/Smoker-Data-WebApp/src/main/java/app/rest/dao/SmokerTrendDao.java:[14,40] cannot find symbol
  symbol: class ISmokerTrendDao
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.242 s
[INFO] Finished at: 2016-01-03T11:03:45-05:00
[INFO] Final Memory: 19M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project Smoker-Data-WebApp: Compilation failure
[ERROR] /Users/stevefeldman/Projects/candidates/Smoker-Data-WebApp/src/main/java/app/rest/dao/SmokerTrendDao.java:[14,40] cannot find symbol
[ERROR] symbol: class ISmokerTrendDao
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project Smoker-Data-WebApp: Compilation failure
/Users/stevefeldman/Projects/candidates/Smoker-Data-WebApp/src/main/java/app/rest/dao/SmokerTrendDao.java:[14,40] cannot find symbol
  symbol: class ISmokerTrendDao

```
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
/Users/stevefeldman/Projects/candidates/Smoker-Data-WebApp/src/main/java/app/rest/dao/SmokerTrendDao.java:[14,40] cannot find symbol
  symbol: class ISmokerTrendDao

```
at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:858)
at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
... 19 more
```

[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
steves-mbp:Smoker-Data-WebApp stevefeldman$

**Comment by JH3P** [comment]
Hey Steve,

Sorry about that, im currently out and won't be near a computer until later
this evening. I'll resolve it as soon as possible.

-Jee

**Comment by SteveFeldman** [comment]
Looks like your last commit fixed the compilation issue...You can consider this issue closed ;)

**Comment by SteveFeldman** [comment]
Feel free to close.
